### PR TITLE
Update the DHT on received ping

### PR DESCRIPTION
**Pull request by b-m-f**
I have a few questions on this: 
- Should the `connection_updated` also be called when ENR sequence that was received? Or will this be done when the requested new ENR is returned?
- Could it happen that a PING is received for which no ENR can be found?

### CODE REVIEW

**Comment by AgeManning** [comment]
Nice work!

I think the `connection_updated` function should be called without supplying the ENR. If we supply the ENR, then it can add the node to the DHT if it doesn't already exist. There could be some edge cases where we receive a PONG from a node which we haven't already added. Simply supplying `None` should fix this issue. This way, we can be sure that a PONG response only updates the `connection_status` of a peer and wont accidentally add new ones. 

ENR's can get updated locally. The PING mechanism routinely sends the local ENR seq number. When a peer sends us a seq number that is newer than what we know about, we ask them to send us their new ENR (via a Find_Nodes(distatance = 1) request). A `Find_Nodes` response updates the DHT, so the resulting ENR should update the connection status and ENR of the peer. 

For your second question, I think it could be possible, but unlikely. ENR's are stored in our DHT or temporarily in queries. I think it could happen that we send a regular PING to a connected node and either timeout from it, or remove that peer from the DHT due to the bucket being full and adding a new peer. A resultant PONG may return, in which case we don't know of the ENR. 

After looking through this code, I've also noticed some other things that should be modified. The known_peer_ids mapping grows indefinitely, which I'll need to bound or prune. Also, I should make sure the entries in the buckets are being handled correctly such that old peers are removed a new ones added. 

In regards to testing, some of the tests are quite long, so I've been putting them in a directory under the structs name. For behaviour, they are: `behaviour/test.rs`. Currently these build entire swarms, but to test the PONG response, we could just use the functions on the behaviour struct. I.e add some enr's with `add_enr` then `handle_rpc_request` to ensure functionality. 

I intend to review this entire implementation some stage soon to clean it up a bit, when async/await becomes stable

**Comment by b-m-f** [comment]
Thanks for the explanation @AgeManning. I have changed it to None for the ENR.

Regarding the tests I got stuck in 2 places.

1. `handle_rpc_response` is not available from the outside. Should I put the test inside the file to make this work?
2. When creating a new `Discv5` struct like this:
```
  let keypair = identity::Keypair::generate_secp256k1();
    let ip: IpAddr = "127.0.0.1".parse().unwrap();
    let enr = EnrBuilder::new("v4")
        .ip(ip.clone().into())
        .udp(500)
        .build(&keypair)
        .unwrap();

    let discv5 = Discv5::new(enr, keypair.clone(), ip.into()).unwrap();
```
I get an error because of the `<TSubstream>` type, which cant be inferred. Can I just use anything here, since its just used on the [PhantomData marker](https://github.com/sigp/rust-libp2p/blob/discv5/misc/discv5/src/behaviour.rs#L91)?

**Comment by AgeManning** [comment]
Hey, sorry for the late reply. I'm still travelling. Will be back on deck in a week and can thoroughly go through all of this. 

For 1. - Yep we should add tests inside the file to access the private functions. 

2. `TSubstream` has to be something that implements `AsyncRead + AsyncWrite`. It's used for a `DummyProtocolHandler` but I think in the future I can remove this type from the Discv5 trait, will likely do this when I get back to avoid these headaches in the future. 
A mutable reference to something implements these traits, as does a Box of something, if you want to insert a dummy type.

**Comment by b-m-f** [comment]
Hi, I am unfortunately quite busy this week. Ill be able to finish this up on the weekend :)

**Comment by b-m-f** [comment]
@AgeManning I managed to write a test that sets up a fake Discv5 with one disconnected peer.
Then I handle a fake PING and expect the Node to become Connected in the KBucketsTable.

I hope it makes sense. Do you see any way of doing it neater?

**Pull request merged**
